### ISSUE TITLE
Kezdőlapi fejléces képek újjítása 2024-esekre In progress

### ISSUE THREAD

**Issue by reDEIfabbri** [reDEIfabbri/SeraTest#3]
- A fejléc képeit kéne ideiekre cserélni

#ToDo:
 - [x] Olyan képeket keresni amiket le lehet vágni az ultra széles képarányra *(3480:1233)* *In progress*
 - [x] Megvágni őket *In progress*
 - [x] jpeg-ből webp-be konvertálni őket és tömöríteni min 75%-ra *In progress*
 - [x] A HTML-t updatelni
 - [x] lokál teszt
 - [x] commit, push, deploy
 - [x] csekkolni!

**Comment by reDEIfabbri** [comment]
# Mekkkcsinálva!
