### ISSUE TITLE
kapcsolatoknál nem látszik az emailcím végig?

### ISSUE THREAD

**Issue by reDEIfabbri** [reDEIfabbri/SeraTest#4]
- Valószínüleg a képernyő/canvas felbontáshoz köthető probléma amit css-ben lehet orvosolni.
 - mobilon én is tapasztaltam, de mivel kattintható linkként van ott, így eddig nem volt fókuszban

# ToDo:
 - [x] ellenőrini
 - [x] okot megállapítani
 - [x] szűrni/tesztelni a megállapított ok helyességét
 - [x] megoldás tervezés
 - [x] update-elni a css-t és szükségszerint a html-t
 - [x] lokál teszt
 - [x] commit, push, deploy
 - [x] csekkolni a megoldás működését élesben!

**Comment by reDEIfabbri** [comment]
A screen szélesség-hezkötött részben kellett
~~~
div.footing > footer#left {
        font-size: large;
    }
~~~

eredetileg 3vw volt ami úgy tűnik túl nagy volt.
