### ISSUE TITLE
új Naptárak kitevése

### ISSUE THREAD

**Issue by reDEIfabbri** [reDEIfabbri/SeraTest#5]
- Kikéne tenni az új naptárakat
 - frissíteni a google naptárat
 
# ToDo:
 - [x] Megkeresni a naptár képeket
 - [x] Letölteni őket
 - [x] Update-elni a html-t
 - [x] lokál teszt
 - [x] commit, push, deploy
 - [x] csekkolni!

**Comment by reDEIfabbri** [comment]
# Sikeresen frissítve!
