### ISSUE TITLE
DB: Bori és Marci után a mos-k legyenek abc rendben

### ISSUE THREAD

**Issue by reDEIfabbri** [reDEIfabbri/SeraTest#6]
- ABC sorrendbe kéne rendezni a diákbizottságot az első kettő után

# ToDo:
 - [x] megállapítani helyes sorrendet
 - [x] e szerint módosítani a html-t
 - [x] lokál teszt
 - [x] commit, deploy, push
 - [x] csekkolni

**Comment by reDEIfabbri** [comment]
Kéccc
